using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

namespace Assets.Scripts
{
    public class MaterialBuilder
    {
        private AtlasBuilder atlasBuilder = new AtlasBuilder();
        private int _tilesPerSide;
        public float Scale { get; private set; }

        public Material MakeMaterial(MeshFilter[] meshFilters, int atlasResolution)
        {

          _tilesPerSide=  Mathf.CeilToInt(Mathf.Sqrt(meshFilters.Length));
            var tileDimension = atlasResolution / _tilesPerSide;
           Scale = 1.0f / _tilesPerSide;

            Material resultMaterial = new Material(Shader.Find("Standard"));
            resultMaterial.name = "Generated by MaterialBuilder Material";
            resultMaterial.mainTexture = atlasBuilder.MakeTexture(meshFilters, atlasResolution, _tilesPerSide, tileDimension);
            return resultMaterial;
        }

        public Dictionary<Rect, GameObject> ClickMap()
        {
            return atlasBuilder.ClickMap;
        }

        public Dictionary<int, Vector2> TextureOffsets()
        {
            return atlasBuilder.TextureOffsets;
        }
    }
}